# Generated by Django 4.1.5 on 2023-03-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default='defualt/blog.jpg', upload_to='images'),
        ),
    ]
